### ISSUE TITLE
AssertionError: no checkpoint files found in Meta-Llama-3-8B-Instruct/

### ISSUE THREAD

**Issue by Nagato-Yk** [meta-llama/llama3#109]

**Comment by xiaoToby** [comment]
![image](https://github.com/meta-llama/llama3/assets/40045458/2a9b3fa5-233c-47f1-8592-e4956d35651d)

**Comment by zhang-sir029** [comment]
> Check if the path Meta-Llama-3-8B-Instruct/ exists and that the directory must contain a .pth model file.

how to get the .pth model file.  
the log：(Llama3) zyq@zyq-MS-7D89:/home/satadisk/llama3$ torchrun --nproc_per_node 1 example_chat_completion.py  --ckpt_dir /home/satadisk/Meta-Llama-3-8B/ \     --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model --max_seq_len 512 --max_batch_size 
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/satadisk/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/satadisk/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/home/satadisk/llama3/llama/generation.py", line 85, in build
    assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
AssertionError: no checkpoint files found in /home/satadisk/Meta-Llama-3-8B/
[2024-04-22 23:40:49,623] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2147254) of binary: /home/zyq/anaconda3/envs/Llama3/bin/python
Traceback (most recent call last):
  File "/home/zyq/anaconda3/envs/Llama3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zyq/anaconda3/envs/Llama3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-22_23:40:49
  host      : zyq-MS-7D89
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2147254)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Kenshinhu** [comment]
Maybe try running the command without any spaces following the '\', as this could be escaping the character and not finding the checkpoint files. Could you try either of the following:

Run the command in one line :
torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir Meta-Llama-3-8B-Instruct/  --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 6

Or without any trailing spaces :
torchrun --nproc_per_node 1 example_chat_completion.py \--ckpt_dir Meta-Llama-3-8B-Instruct/ \--tokenizer_path tokenizer.model \--max_seq_len 512 --max_batch_size 6

**Comment by lingfengchencn** [comment]
> Check if the path Meta-Llama-3-8B-Instruct/ exists and that the directory must contain a .pth model file.

there is no .pth filesl . all models are :
[model-00001-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00001-of-00004.safetensors)
[model-00002-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00002-of-00004.safetensors)
....

**Comment by Hyccccccc** [comment]
I meet the same problem. Have you solved that?

**Comment by Hyccccccc** [comment]
I meet the same problem. Have you solved that?

> > Check if the path Meta-Llama-3-8B-Instruct/ exists and that the directory must contain a .pth model file.
> 
> there is no .pth filesl . all models are : [model-00001-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00001-of-00004.safetensors) [model-00002-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00002-of-00004.safetensors) ....

**Comment by Hyccccccc** [comment]
> > Check if the path Meta-Llama-3-8B-Instruct/ exists and that the directory must contain a .pth model file.
> 
> there is no .pth filesl . all models are : [model-00001-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00001-of-00004.safetensors) [model-00002-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00002-of-00004.safetensors) ....

I meet the same problem. Have you solved that?

**Comment by lingfengchencn** [comment]
> > > Check if the path Meta-Llama-3-8B-Instruct/ exists and that the directory must contain a .pth model file.
> > 
> > 
> > there is no .pth filesl . all models are : [model-00001-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00001-of-00004.safetensors) [model-00002-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00002-of-00004.safetensors) ....
> 
> I meet the same problem. Have you solved that?

Sure! Thanks for asking. I looked into it, and it turns out that if you clone from Hugging Face, you'll find the `.pth` file in the `Meta-Llama-3-8B-Instruct/original` folder, just like the readme says.

```bash
huggingface-cli download meta-llama/Meta-Llama-3-8B-Instruct --include "original/*" --local-dir meta-llama/Meta-Llama-3-8B-Instruct
```

**Meta-Llama-3-8B-Instruct/original** 😂

**Comment by Hyccccccc** [comment]
I got it !! Thank you so much !!!

> > > > Check if the path Meta-Llama-3-8B-Instruct/ exists and that the directory must contain a .pth model file.
> > > 
> > > 
> > > there is no .pth filesl . all models are : [model-00001-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00001-of-00004.safetensors) [model-00002-of-00004.safetensors](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/model-00002-of-00004.safetensors) ....
> > 
> > 
> > I meet the same problem. Have you solved that?
> 
> Sure! Thanks for asking. I looked into it, and it turns out that if you clone from Hugging Face, you'll find the `.pth` file in the `Meta-Llama-3-8B-Instruct/original` folder, just like the readme says.
> 
> ```shell
> huggingface-cli download meta-llama/Meta-Llama-3-8B-Instruct --include "original/*" --local-dir meta-llama/Meta-Llama-3-8B-Instruct
> ```
> 
> **Meta-Llama-3-8B-Instruct/original** 😂
> 
> so the command is:
> 
> ```shell
> torchrun --nproc_per_node 1 example_chat_completion.py \
>     --ckpt_dir /data/storage/Meta-Llama-3-8B/original \
>     --tokenizer_path /data/storage/Meta-Llama-3-8B/original/tokenizer.model \
>     --max_seq_len 512 --max_batch_size 6
> ```

**Comment by WishingWell13** [comment]
If I have a fine tuned model without `.pth` files available (only `safetensor`), is there a solution available?

**Comment by lingfengchencn** [comment]
> If I have a fine tuned model without `.pth` files available (only `safetensor`), is there a solution available?
> 
> It was a model originally fine tuned using LlamaFactory. All the google searches are directing me towards the `llama.cpp` repository, but I was wondering if there was a solution here.

use safetensors to convert safetensor to pth??

**Comment by guotong1988** [comment]
> use safetensors to convert safetensor to pth??

Thank you.
