### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by s084088** [meta-llama/llama3#127]
System : Window 11
CPU : I9
Memory : 64G
GPU : RTX 4080
CUDA : 12.4

This is my execution process, I don't know why he failed.

```
conda create -n llama3 python=3.10

conda activate llama3

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

pip install -e .

torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir Meta-Llama-3-8B-Instruct/ --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model --max_seq_len 512 --max_batch_size 6
```

```
(D:\Caches\Conda\conda_envs\llama3) PS E:\ai\models\llama\llama3> torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir Meta-Llama-3-8B-Instruct/ --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model --max_seq_len 512 --max_batch_size 6
[2024-04-23 13:27:20,383] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[W socket.cpp:697] [c10d] The client socket has failed to connect to [activate.navicat.com]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [activate.navicat.com]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [activate.navicat.com]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\distributed_c10d.py:608: UserWarning: Attempted to get default timeout for nccl backend, but NCCL support is not compiled
  warnings.warn("Attempted to get default timeout for nccl backend, but NCCL support is not compiled")
[W socket.cpp:697] [c10d] The client socket has failed to connect to [activate.navicat.com]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [activate.navicat.com]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W socket.cpp:697] [c10d] The client socket has failed to connect to [activate.navicat.com]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Traceback (most recent call last):
  File "E:\ai\models\llama\llama3\example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\ai\models\llama\llama3\example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "E:\ai\models\llama\llama3\llama\generation.py", line 68, in build
    torch.distributed.init_process_group("nccl")
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\distributed_c10d.py", line 1184, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\distributed_c10d.py", line 1302, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2024-04-23 13:27:25,459] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 8528) of binary: D:\Caches\Conda\conda_envs\llama3\python.exe
Traceback (most recent call last):
  File "D:\Caches\Conda\conda_envs\llama3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Caches\Conda\conda_envs\llama3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Caches\Conda\conda_envs\llama3\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\run.py", line 812, in main
    run(args)
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\run.py", line 803, in run
    elastic_launch(
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\launcher\api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\Caches\Conda\conda_envs\llama3\lib\site-packages\torch\distributed\launcher\api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-23_13:27:25
  host      : Nemo_Work
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8528)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by srimouli04** [comment]
Could you check your CUDA installation? The NCCL error generally occurs when you have a CUDA incompatibility. Try updating your drivers, and this should be fixed in the majority of the cases.

**Comment by ccozad** [comment]
I believe I ran into a similar problem as documented in  #132

**Comment by HamidShojanazeri** [comment]
can you please  check here and use `torch.distributed.init_process_group(backend='gloo'` to see if that work.
https://github.com/meta-llama/llama3/blob/main/llama/generation.py#L68

**Comment by ccozad** [comment]
@HamidShojanazeri Running this code

```python
import os
import torch

check_point_directory = "<path>"
tokenizer_path = "<path>"
temperature = 0.6 # How much randomness is included in model output
top_p = 0.9 # Top-p probability threshold for nucleus sampling
max_sequence_length = 512 # The llama 3 model model produces up to 8192 tokens so max sequence length needs to be <= 8192
max_batch_size = 4
model_parallel_size = 1

os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12355'
#os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["RANK"] = "0"
os.environ["WORLD_SIZE"] = "1"

if not torch.distributed.is_initialized():
    torch.distributed.init_process_group(backend='gloo')

# Initialize the model
generator = Llama.build(
    ckpt_dir = check_point_directory,
    tokenizer_path = tokenizer_path,
    max_seq_len = max_sequence_length,
    max_batch_size = max_batch_size,
    model_parallel_size = model_parallel_size
)
````

produced this result

```
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1

Loaded in 16.51 seconds
```

So that's promising!

**Comment by s084088** [comment]
> @s084088 as you running on Windows, can you please check [here](https://github.com/meta-llama/llama3/blob/main/llama/generation.py#L68) and use to see if that work.`torch.distributed.init_process_group(backend='gloo'`

Great! It's working!
