### ISSUE TITLE
Does 70B model need to use 8 gpu cards?

### ISSUE THREAD

**Issue by xiaoToby** [meta-llama/llama3#164]
I have 4 A800 gpus now, and downloaded the 70B/instruct model.
I use this command to do the inference, torchrun --nproc_per_node 8 example_chat_completion.py     --ckpt_dir /home/llama3/models/Meta-Llama-3-70B-Instruct/     --tokenizer_path /home/llama3/models/Meta-Llama-3-70B-Instruct/tokenizer.model     --max_seq_len 512 --max_batch_size 6
but there are errors, the error logs are below:
[2024-04-28 07:31:06,024] torch.distributed.run: [WARNING] 
[2024-04-28 07:31:06,024] torch.distributed.run: [WARNING] *****************************************
[2024-04-28 07:31:06,024] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-04-28 07:31:06,024] torch.distributed.run: [WARNING] *****************************************
> initializing model parallel with size 8
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/home/llama3/llama/generation.py", line 75, in build
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/home/llama3/llama/generation.py", line 75, in build
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/home/llama3/llama/generation.py", line 75, in build
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/home/llama3/llama/generation.py", line 75, in build
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/home/llama3/llama/generation.py", line 75, in build
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 408, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-04-28 07:31:11,045] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3375 closing signal SIGTERM
[2024-04-28 07:31:11,045] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3376 closing signal SIGTERM
[2024-04-28 07:31:11,051] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3377 closing signal SIGTERM
[2024-04-28 07:31:11,795] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 3 (pid: 3378) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-28_07:31:11
  host      : 830808195c6d
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 3379)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-28_07:31:11
  host      : 830808195c6d
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 3380)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-28_07:31:11
  host      : 830808195c6d
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 3381)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-04-28_07:31:11
  host      : 830808195c6d
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 3382)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-28_07:31:11
  host      : 830808195c6d
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3378)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

I already set --nproc_per_node 8.
My guesss is that , does 70B model need to use 8 gpu cards?

**Comment by Lynn1** [comment]
yes, I think they use "Horizontal Model Sharding"

**Comment by Lynn1** [comment]
I think I'vd solved the problem( to reconcate the 8 shards to support running on 2x80GB or 4x40GB GPUs), you can use my script here: [concat_llama3_70Bf.py](https://github.com/Lynn1/llama3-on-2GPUs)

**Comment by xiaoToby** [comment]
> Yes, running the 70B needs 8 GPUs as it has 8 shards. You can run it on a different number of GPUs via huggingface.

How to run it on a different number of GPUs via huggingface? @subramen

**Comment by Genie-Kim** [comment]
I wonder about this. I would appreciate it if you could answer this.

**Comment by subramen** [comment]
https://github.com/meta-llama/llama3?tab=readme-ov-file#access-to-hugging-face
