### ISSUE TITLE
Redirects are currently not supported in Windows or MacOs

### ISSUE THREAD

**Issue by xingchaoet** [meta-llama/llama3#196]
torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir Meta-Llama-3-8B-Instruct --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model  --max_seq_len 512 --max_batch_size 6
[2024-05-08 08:37:17,241] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[W socket.cpp:663] [c10d] The client socket has failed to connect to [iprotect.cloudcore.cn]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W socket.cpp:663] [c10d] The client socket has failed to connect to [iprotect.cloudcore.cn]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\new_space\github\ai\llama3\example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "D:\tools\Python3106\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\tools\Python3106\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\tools\Python3106\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\new_space\github\ai\llama3\example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "E:\new_space\github\ai\llama3\llama\generation.py", line 68, in build
    torch.distributed.init_process_group("nccl")
  File "D:\tools\Python3106\lib\site-packages\torch\distributed\c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "D:\tools\Python3106\lib\site-packages\torch\distributed\distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "D:\tools\Python3106\lib\site-packages\torch\distributed\distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2024-05-08 08:37:22,314] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 22332) of binary: D:\tools\Python3106\python.exe
Traceback (most recent call last):
  File "D:\tools\Python3106\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\tools\Python3106\lib\runpy.py", line 86, in _run_code

**Comment by fbnav** [comment]
Hi, it looks like you are running this on Windows. NCCL isn't supported on Windows. Can you please check [here](https://github.com/meta-llama/llama3/blob/main/llama/generation.py#L68) and use torch.distributed.init_process_group(backend='gloo') and try if it works?

**Comment by jhyangkorea** [comment]
I have the same problem. So I tried with replacing torch.distributed.init_process_group("nccl") with torch.distributed.init_process_group(backend='gloo'). However it incurs the same error.

**Comment by fbnav** [comment]
Hi, this might be because you may be using a version of PyTorch that is not compatible with your CUDA version. Could you try `pip install torch --upgrade` to try upgrading to a newer version of PyTorch that supports the `_cuda_setDevice` attribute? Or you can try reinstalling PyTorch and running it again. You can do it from here : [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/)

Also linking a similar issue where replacing the backend with `gloo` worked on Windows OS for reference : [https://github.com/meta-llama/llama3/issues/127](https://github.com/meta-llama/llama3/issues/127)

For this repo specifically, the example scripts are for running inference on single (for 8B) and multi (for 70B) GPU setups using CUDA, but Windows is not currently supported. Feel free to check out the examples on the llama-recipes repo for running Llama locally via hugging face or ollama: [https://github.com/meta-llama/llama-recipes/tree/main/recipes/quickstart/Running_Llama3_Anywhere](https://github.com/meta-llama/llama-recipes/tree/main/recipes/quickstart/Running_Llama3_Anywhere)
