### ISSUE TITLE
Llama3-8B-Instruct crashes after processing multiple consecutive queries

### ISSUE THREAD

**Issue by MatrixDoge** [meta-llama/llama3#63]
llama3-8B-instruct will crash **every time** after I ask the following 3 questions consecutively in a conversation dialog. 

I ask these 3 questions no matter what the response was:
1.write python function to calculate nth fibbonacci number
2.use dynamic programming
3.continue
[crash]

My GPU VRAM usage was 17GB/24GB before crash, the system memory usage was not high either before crash.
I cannot get the error message of why it crashed from the terminal output

if my questions are simple, llama3 can survive further:
1.answer of 1+1
2.answer of 1+2
3.answer of 1+3
4.answer of 1+4
5.answer of 1+5
...

I modified the example "example_chat_completion.py" to just focus on one conversation:
https://gist.github.com/MatrixDoge/5b07427f7cf3036bf4475a2618013364

the terminal log
~~~
(venv) testuser@testuser-gpu:/media/testuser/windows-drive/Projects/meta/llama3$ torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir Meta-Llama-3-8B-Instruct/     --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model     --max_seq_len 512 --max_batch_size 6
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/__init__.py:696: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
Loaded in 18.65 seconds
Your prompt:write python function to calculate nth fibbonacci number

==================================

Role:assistant
Content:Here is a simple Python function to calculate the nth Fibonacci number:
```
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)
```
This function uses a recursive approach to calculate the Fibonacci number. It works by calling itself with smaller values of `n` until it reaches the base case of `n <= 1`, at which point it returns the value of `n`.

However, this function has a time complexity of O(2^n), which means it becomes very slow for large values of `n`. A more efficient approach is to use an iterative approach, like this:
```
def fibonacci(n):
    if n <= 1:
        return n
    a, b = 0, 1
    for i in range(2, n+1):
        a, b = b, a + b
    return b
```
This function uses a loop to iterate from 2 to `n`, and at each iteration, it updates the values of `a` and `b` to be the next two Fibonacci numbers. The final value of `b` is the `n`-th Fibonacci number.

You can test these functions with a value of `n`, like this:
```
print(fibonacci(10))  # prints 55
```
Note that the iterative approach is much faster than the recursive approach for large values of `n`.

==================================

[{'role': 'user', 'content': 'write python function to calculate nth fibbonacci number'}, {'role': 'assistant', 'content': 'Here is a simple Python function to calculate the nth Fibonacci number:\n```\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        return fibonacci(n-1) + fibonacci(n-2)\n```\nThis function uses a recursive approach to calculate the Fibonacci number. It works by calling itself with smaller values of `n` until it reaches the base case of `n <= 1`, at which point it returns the value of `n`.\n\nHowever, this function has a time complexity of O(2^n), which means it becomes very slow for large values of `n`. A more efficient approach is to use an iterative approach, like this:\n```\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for i in range(2, n+1):\n        a, b = b, a + b\n    return b\n```\nThis function uses a loop to iterate from 2 to `n`, and at each iteration, it updates the values of `a` and `b` to be the next two Fibonacci numbers. The final value of `b` is the `n`-th Fibonacci number.\n\nYou can test these functions with a value of `n`, like this:\n```\nprint(fibonacci(10))  # prints 55\n```\nNote that the iterative approach is much faster than the recursive approach for large values of `n`.'}]
Your prompt:use dynamic programming

==================================

Role:assistant
Content:Here is a Python function that uses dynamic programming to calculate the nth Fibonacci number:
```
def fibonacci(n):
    if n <= 1:
        return n

    fib_values = [0] * (n + 1)
    fib_values[0] = 0
    fib_values[1] = 1

    for i in range(2, n + 1):
        fib_values[i] = fib_values[i-1] + fib_values[i-2]

    return fib_values[n]
```
This function uses a list `fib_values` to store the Fibonacci numbers as they are calculated. The list is initialized with `n+1` elements, all set to 0.

The function then iterates from 2 to `n`, and at each iteration, it calculates the `i`-th Fibonacci number by adding the `(i-1

==================================

[{'role': 'user', 'content': 'write python function to calculate nth fibbonacci number'}, {'role': 'assistant', 'content': 'Here is a simple Python function to calculate the nth Fibonacci number:\n```\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        return fibonacci(n-1) + fibonacci(n-2)\n```\nThis function uses a recursive approach to calculate the Fibonacci number. It works by calling itself with smaller values of `n` until it reaches the base case of `n <= 1`, at which point it returns the value of `n`.\n\nHowever, this function has a time complexity of O(2^n), which means it becomes very slow for large values of `n`. A more efficient approach is to use an iterative approach, like this:\n```\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for i in range(2, n+1):\n        a, b = b, a + b\n    return b\n```\nThis function uses a loop to iterate from 2 to `n`, and at each iteration, it updates the values of `a` and `b` to be the next two Fibonacci numbers. The final value of `b` is the `n`-th Fibonacci number.\n\nYou can test these functions with a value of `n`, like this:\n```\nprint(fibonacci(10))  # prints 55\n```\nNote that the iterative approach is much faster than the recursive approach for large values of `n`.'}, {'role': 'user', 'content': 'use dynamic programming'}, {'role': 'assistant', 'content': 'Here is a Python function that uses dynamic programming to calculate the nth Fibonacci number:\n```\ndef fibonacci(n):\n    if n <= 1:\n        return n\n\n    fib_values = [0] * (n + 1)\n    fib_values[0] = 0\n    fib_values[1] = 1\n\n    for i in range(2, n + 1):\n        fib_values[i] = fib_values[i-1] + fib_values[i-2]\n\n    return fib_values[n]\n```\nThis function uses a list `fib_values` to store the Fibonacci numbers as they are calculated. The list is initialized with `n+1` elements, all set to 0.\n\nThe function then iterates from 2 to `n`, and at each iteration, it calculates the `i`-th Fibonacci number by adding the `(i-1'}]
Your prompt:continue
Traceback (most recent call last):
  File "/media/testuser/windows-drive/Projects/meta/llama3/example_chat_completion.py", line 113, in <module>
    fire.Fire(main)
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/media/testuser/windows-drive/Projects/meta/llama3/example_chat_completion.py", line 80, in main
    results = generator.chat_completion(
  File "/media/testuser/windows-drive/Projects/meta/llama3/llama/generation.py", line 309, in chat_completion
    generation_tokens, generation_logprobs = self.generate(
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/testuser/windows-drive/Projects/meta/llama3/llama/generation.py", line 151, in generate
    assert max_prompt_len <= params.max_seq_len
AssertionError
[2024-04-19 02:25:37,235] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 6292) of binary: /media/testuser/windows-drive/Projects/meta/llama3/venv/bin/python3
Traceback (most recent call last):
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/testuser/windows-drive/Projects/meta/llama3/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-19_02:25:37
  host      : testuser-gpu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6292)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
~~~

my machine spec
```
OS: Ubuntu 22.04.4 LTS x86_64 
Kernel: 6.5.0-27-generic 
Uptime: 44 mins 
Packages: 2343 (dpkg), 12 (snap) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 2560x1080 
DE: GNOME 42.9 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: 13th Gen Intel i9-13900K (32) @ 5.500GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 2684 
Memory: 4426MiB / 31823MiB 

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
| 30%   51C    P2             258W / 450W |  16727MiB / 24564MiB |     99%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1454      G   /usr/lib/xorg/Xorg                          154MiB |
|    0   N/A  N/A      1670      G   /usr/bin/gnome-shell                        101MiB |
|    0   N/A  N/A      3360      G   ...irefox/3836/usr/lib/firefox/firefox      137MiB |
|    0   N/A  N/A      4898      C   ...ojects/meta/llama3/venv/bin/python3    16312MiB |
+---------------------------------------------------------------------------------------+
python --version
Python 3.10.12
pip list
Package                  Version    Editable project location
------------------------ ---------- -------------------------------------------------
blobfile                 2.1.1
certifi                  2024.2.2
charset-normalizer       3.3.2
fairscale                0.4.13
filelock                 3.13.4
fire                     0.6.0
fsspec                   2024.3.1
idna                     3.7
Jinja2                   3.1.3
llama3                   0.0.1      /media/testuser/windows-drive/Projects/meta/llama3
lxml                     4.9.4
MarkupSafe               2.1.5
mpmath                   1.3.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.1.105
pip                      22.0.2
pycryptodomex            3.20.0
regex                    2024.4.16
requests                 2.31.0
setuptools               59.6.0
six                      1.16.0
sympy                    1.12
termcolor                2.4.0
tiktoken                 0.4.0
torch                    2.2.2
triton                   2.2.0
typing_extensions        4.11.0
urllib3                  2.2.1

-----------------------------------------------------------------------------------------
sudo dmidecode --type 17
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.4.0 present.

Handle 0x004C, DMI type 17, 92 bytes
Memory Device
	Array Handle: 0x004B
	Size: No Module Installed

Handle 0x004D, DMI type 17, 92 bytes
Memory Device
	Array Handle: 0x004B
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 16 GB
	Form Factor: DIMM
	Locator: Controller0-ChannelA-DIMM1
	Bank Locator: BANK 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 3200 MT/s
	Manufacturer: G Skill Intl
	Serial Number: 00000000
	Asset Tag: 9876543210
	Part Number: F4-3200C14-16GVR    
	Rank: 2
	Configured Memory Speed: 3200 MT/s
	Minimum Voltage: 1.2 V
	Maximum Voltage: 1.35 V
	Configured Voltage: 1.2 V
	Memory Technology: DRAM
	Memory Operating Mode Capability: Volatile memory
	Module Manufacturer ID: Bank 5, Hex 0xCD
	Volatile Size: 16 GB

Handle 0x004E, DMI type 17, 92 bytes
Memory Device
	Array Handle: 0x004B
	Size: No Module Installed

Handle 0x004F, DMI type 17, 92 bytes
Memory Device
	Array Handle: 0x004B
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 16 GB
	Form Factor: DIMM
	Locator: Controller1-ChannelA-DIMM1
	Bank Locator: BANK 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 3200 MT/s
	Manufacturer: G Skill Intl
	Serial Number: 00000000
	Asset Tag: 9876543210
	Part Number: F4-3200C14-16GVR    
	Rank: 2
	Configured Memory Speed: 3200 MT/s
	Minimum Voltage: 1.2 V
	Maximum Voltage: 1.35 V
	Configured Voltage: 1.2 V
	Memory Technology: DRAM
	Memory Operating Mode Capability: Volatile memory
	Module Manufacturer ID: Bank 5, Hex 0xCD
	Volatile Size: 16 GB
```

**Comment by MatrixDoge** [comment]
reason: max rompt length exceeded the max seq length
