### ISSUE TITLE
Issues Running Llama 3 on MacBook Pro M3 - NCCL Backend Not Supported

### ISSUE THREAD

**Issue by suntereo** [meta-llama/llama3#75]
Hello Meta,

I am attempting to run Llama 3 locally for the first time using a MacBook Pro with the M3 chip. I've followed the quick start guide available [here](https://github.com/meta-llama/llama3?tab=readme-ov-file#quick-start), but I am running into a critical issue during the last step (Step 6, the `torchrun` command).

Here is the error I encounter when I execute the `torchrun` command:

```plaintext
[2024-04-18 16:19:17,085] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:608: UserWarning: Attempted to get default timeout for nccl backend, but NCCL support is not compiled
  warnings.warn("Attempted to get default timeout for nccl backend, but NCCL support is not compiled")
Traceback (most recent call last):
  File "/Users/shawn/Downloads/llama3-git/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/shawn/Downloads/llama3-git/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
  File "/Users/shawn/Downloads/llama3-git/llama3/llama/generation.py", line 68, in build
    torch.distributed.init_process_group("nccl")
  File "/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1184, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/opt/miniconda3/envs/llama3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1302, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
```

It appears that macOS does not support the NCCL backend used by default in many PyTorch distributed processes, and I have been unable to find a way to configure the system to use the `gloo` backend for local operations on macOS.

Any guidance on how to resolve this issue or recommendations for running Llama 3 on a MacBook would be greatly appreciated. Thank you in advance for your help!

**Comment by deboradum** [comment]
check out https://huggingface.co/mlx-community/Meta-Llama-3-70B-4bit

**Comment by suntereo** [comment]
Thanks. I was able to get it running with LM Studio (https://lmstudio.ai)

**Comment by itsmesatwik** [comment]
I was running the Llama 3 - 8B Instruct with LM Studio but somehow it doesn't know that it is Llama 3.
Saw this thread since I was running into the same issue `raise RuntimeError("Distributed package doesn't have NCCL built in")`
Are we sure it is Llama3?
